version: 0.1

phases:
  install:
    commands:
      - sudo apt-get autoclean
      - sudo apt-get update -y
      - sudo apt-get install -yf maven
      - sudo java -version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - sudo /usr/bin/mvn -version
  build:
    commands:
      - echo Build started on `date`
      - echo mvn version `mvn -version`
      - sudo /usr/bin/mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/demo-0.0.1.jar
  discard-paths: yes  