version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo mvn version `mvn -version`
  build:
    commands:
      - echo Build started on `date`
      - echo mvn version `mvn -version`
      - sudo mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/demo-0.0.1.jar
  discard-paths: yes